version: "3.7"
services:
  app:
    image: openregistry/open-registry:0.1.0
    working_dir: /app
    volumes:
      - .:/app
      - lein-deps:/root/.m2
    command: lein repl :headless :start :host 0.0.0.0 :port 33333
    ports:
      - 9010:9010
    environment:
      - PORT=5432
      - METRICS_PORT=2345
      - SERVER_THREADS=16
      - IPFS_API=/ip4/ipfs/tcp/5001
      - REGISTRY_URL=http://npm.open-registry.test:2015
      - SERVER_DEV=true
    restart: always
  metrics:
    image: prom/prometheus:v2.9.1
    volumes:
      - prometheus:/prometheus
      - ./infra/prometheus.yml:/prometheus.yml
    command: --config.file=/prometheus.yml --storage.tsdb.path=/prometheus
    restart: always
  ipfs:
    image: ipfs/go-ipfs:v0.4.19
    environment:
      - IPFS_PROFILE=server,badgerds
    volumes:
      - ipfs:/data/ipfs
    restart: always
  front:
    build:
      context: ./infra/caddy
    ports:
      - 2015:2015
      - 9180:9180
    volumes:
      - ./infra/caddy/Caddyfile:/etc/Caddyfile
      - caddy:/root/.caddy
    restart: always
  dashboard:
    image: grafana/grafana:6.1.4
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    ports:
      - 3000:3000
    volumes:
      - ./infra/grafana/config.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
      - ./infra/grafana/:/etc/grafana/provisioning
    restart: always
  finance:
    image: openregistry/finance-watch:0.1.0
    environment:
      - ADDRESS=0.0.0.0
      - PORT=6000
    ports:
      - 6000:6000
    restart: always
volumes:
  prometheus:
  lein-deps:
  caddy:
  grafana:
  ipfs:
