apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://metrics:9090
  jsonData:
     timeInterval: "1s"
  isDefault: true
  version: 1
  editable: false
